### ISSUE TITLE
Unable to cast default lovelace dashboard with Neerslag Custom card

### ISSUE THREAD

**Issue by clousberg** [aex351/home-assistant-neerslag-app#22]
Neerslag custom card is showing in browser and HA-app, but when casting the same dashboard to my Google Hub (gen 2) via Google Cast integration, I get a custom component not found-error.
Already restarted HASS and Google Hub several times and waited for 24 hours but no positive result.
I also read about possible wrong path to the custom component, but can't place that remark (yet)
Hope a fix can solve this behaviour.

**Comment by aex351** [comment]
I have updated the Neerslag Card. See also https://github.com/aex351/home-assistant-neerslag-card/issues/29. The issue with Home Assistant Cast should now be fixed in the latest update of the Neerslag App.

**Comment by aex351** [comment]
This issue appears to have been resolved.

**Comment by clousberg** [comment]
sorry, still not resolved.

All components of HA and HACS running on the latest version.

![GoogleHub2CastNeerslagcard](https://user-images.githubusercontent.com/87444372/155800337-4c3722f6-5dca-40fb-a79d-e1e383be0725.png)

**Comment by vheijnen** [comment]
I'm having this issue too. How can i help debugging?

**Comment by aex351** [comment]
The `neerslag-card` now has all required dependencies bundled. This should resolve the issue.
